# Edit environment in this file to fit Your setup

version: '3'
services:
    flask:
      build: .
      container_name: flask
      environment:
              - FLASK_APP=server.py
      volumes:
              - ./app:/usr/src/app
      ports:
              - "5000:5000"
      tty: true
      stdin_open: false
      restart: unless-stopped
      command: flask run --host=0.0.0.0

